/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Audioling API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from '@tanstack/react-query';
import { apiInstance } from '../../api-instance.ts';
import type { ErrorType } from '../../api-instance.ts';
import type {
    DeleteApiLibraryIdTracksIdFavorite204,
    DeleteApiLibraryIdTracksIdFavorite401,
    DeleteApiLibraryIdTracksIdFavorite403,
    DeleteApiLibraryIdTracksIdFavorite404,
    DeleteApiLibraryIdTracksIdFavorite500,
    GetApiLibraryIdTracks200,
    GetApiLibraryIdTracks401,
    GetApiLibraryIdTracks403,
    GetApiLibraryIdTracks422,
    GetApiLibraryIdTracks500,
    GetApiLibraryIdTracksId200,
    GetApiLibraryIdTracksId401,
    GetApiLibraryIdTracksId403,
    GetApiLibraryIdTracksId404,
    GetApiLibraryIdTracksId500,
    GetApiLibraryIdTracksParams,
    PostApiLibraryIdTracksIdFavorite204,
    PostApiLibraryIdTracksIdFavorite401,
    PostApiLibraryIdTracksIdFavorite403,
    PostApiLibraryIdTracksIdFavorite404,
    PostApiLibraryIdTracksIdFavorite500,
} from '../audioling-openapi-client.schemas.ts';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary Get all tracks
 */
export const getApiLibraryIdTracks = (
    libraryId: string,
    params: GetApiLibraryIdTracksParams,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<GetApiLibraryIdTracks200>(
        { method: 'GET', params, signal, url: `/api/${libraryId}/tracks` },
        options,
    );
};

export const getGetApiLibraryIdTracksQueryKey = (
    libraryId: string,
    params: GetApiLibraryIdTracksParams,
) => {
    return [`/api/${libraryId}/tracks`, ...(params ? [params] : [])] as const;
};

export const getGetApiLibraryIdTracksQueryOptions = <
    TData = Awaited<ReturnType<typeof getApiLibraryIdTracks>>,
    TError = ErrorType<
        | GetApiLibraryIdTracks401
        | GetApiLibraryIdTracks403
        | GetApiLibraryIdTracks422
        | GetApiLibraryIdTracks500
    >,
>(
    libraryId: string,
    params: GetApiLibraryIdTracksParams,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getApiLibraryIdTracks>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetApiLibraryIdTracksQueryKey(libraryId, params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLibraryIdTracks>>> = ({
        signal,
    }) => getApiLibraryIdTracks(libraryId, params, requestOptions, signal);

    return { enabled: !!libraryId, queryFn, queryKey, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getApiLibraryIdTracks>>,
        TError,
        TData
    > & { queryKey: QueryKey };
};

export type GetApiLibraryIdTracksQueryResult = NonNullable<
    Awaited<ReturnType<typeof getApiLibraryIdTracks>>
>;
export type GetApiLibraryIdTracksQueryError = ErrorType<
    | GetApiLibraryIdTracks401
    | GetApiLibraryIdTracks403
    | GetApiLibraryIdTracks422
    | GetApiLibraryIdTracks500
>;

export function useGetApiLibraryIdTracks<
    TData = Awaited<ReturnType<typeof getApiLibraryIdTracks>>,
    TError = ErrorType<
        | GetApiLibraryIdTracks401
        | GetApiLibraryIdTracks403
        | GetApiLibraryIdTracks422
        | GetApiLibraryIdTracks500
    >,
>(
    libraryId: string,
    params: GetApiLibraryIdTracksParams,
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getApiLibraryIdTracks>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getApiLibraryIdTracks>>,
                    TError,
                    TData
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetApiLibraryIdTracks<
    TData = Awaited<ReturnType<typeof getApiLibraryIdTracks>>,
    TError = ErrorType<
        | GetApiLibraryIdTracks401
        | GetApiLibraryIdTracks403
        | GetApiLibraryIdTracks422
        | GetApiLibraryIdTracks500
    >,
>(
    libraryId: string,
    params: GetApiLibraryIdTracksParams,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getApiLibraryIdTracks>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getApiLibraryIdTracks>>,
                    TError,
                    TData
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetApiLibraryIdTracks<
    TData = Awaited<ReturnType<typeof getApiLibraryIdTracks>>,
    TError = ErrorType<
        | GetApiLibraryIdTracks401
        | GetApiLibraryIdTracks403
        | GetApiLibraryIdTracks422
        | GetApiLibraryIdTracks500
    >,
>(
    libraryId: string,
    params: GetApiLibraryIdTracksParams,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getApiLibraryIdTracks>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get all tracks
 */

export function useGetApiLibraryIdTracks<
    TData = Awaited<ReturnType<typeof getApiLibraryIdTracks>>,
    TError = ErrorType<
        | GetApiLibraryIdTracks401
        | GetApiLibraryIdTracks403
        | GetApiLibraryIdTracks422
        | GetApiLibraryIdTracks500
    >,
>(
    libraryId: string,
    params: GetApiLibraryIdTracksParams,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getApiLibraryIdTracks>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
    const queryOptions = getGetApiLibraryIdTracksQueryOptions(libraryId, params, options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Get track by id
 */
export const getApiLibraryIdTracksId = (
    libraryId: string,
    id: string,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<GetApiLibraryIdTracksId200>(
        { method: 'GET', signal, url: `/api/${libraryId}/tracks/${id}` },
        options,
    );
};

export const getGetApiLibraryIdTracksIdQueryKey = (libraryId: string, id: string) => {
    return [`/api/${libraryId}/tracks/${id}`] as const;
};

export const getGetApiLibraryIdTracksIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getApiLibraryIdTracksId>>,
    TError = ErrorType<
        | GetApiLibraryIdTracksId401
        | GetApiLibraryIdTracksId403
        | GetApiLibraryIdTracksId404
        | GetApiLibraryIdTracksId500
    >,
>(
    libraryId: string,
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getApiLibraryIdTracksId>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetApiLibraryIdTracksIdQueryKey(libraryId, id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLibraryIdTracksId>>> = ({
        signal,
    }) => getApiLibraryIdTracksId(libraryId, id, requestOptions, signal);

    return { enabled: !!(libraryId && id), queryFn, queryKey, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getApiLibraryIdTracksId>>,
        TError,
        TData
    > & { queryKey: QueryKey };
};

export type GetApiLibraryIdTracksIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getApiLibraryIdTracksId>>
>;
export type GetApiLibraryIdTracksIdQueryError = ErrorType<
    | GetApiLibraryIdTracksId401
    | GetApiLibraryIdTracksId403
    | GetApiLibraryIdTracksId404
    | GetApiLibraryIdTracksId500
>;

export function useGetApiLibraryIdTracksId<
    TData = Awaited<ReturnType<typeof getApiLibraryIdTracksId>>,
    TError = ErrorType<
        | GetApiLibraryIdTracksId401
        | GetApiLibraryIdTracksId403
        | GetApiLibraryIdTracksId404
        | GetApiLibraryIdTracksId500
    >,
>(
    libraryId: string,
    id: string,
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getApiLibraryIdTracksId>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getApiLibraryIdTracksId>>,
                    TError,
                    TData
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetApiLibraryIdTracksId<
    TData = Awaited<ReturnType<typeof getApiLibraryIdTracksId>>,
    TError = ErrorType<
        | GetApiLibraryIdTracksId401
        | GetApiLibraryIdTracksId403
        | GetApiLibraryIdTracksId404
        | GetApiLibraryIdTracksId500
    >,
>(
    libraryId: string,
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getApiLibraryIdTracksId>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getApiLibraryIdTracksId>>,
                    TError,
                    TData
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetApiLibraryIdTracksId<
    TData = Awaited<ReturnType<typeof getApiLibraryIdTracksId>>,
    TError = ErrorType<
        | GetApiLibraryIdTracksId401
        | GetApiLibraryIdTracksId403
        | GetApiLibraryIdTracksId404
        | GetApiLibraryIdTracksId500
    >,
>(
    libraryId: string,
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getApiLibraryIdTracksId>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get track by id
 */

export function useGetApiLibraryIdTracksId<
    TData = Awaited<ReturnType<typeof getApiLibraryIdTracksId>>,
    TError = ErrorType<
        | GetApiLibraryIdTracksId401
        | GetApiLibraryIdTracksId403
        | GetApiLibraryIdTracksId404
        | GetApiLibraryIdTracksId500
    >,
>(
    libraryId: string,
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getApiLibraryIdTracksId>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
    const queryOptions = getGetApiLibraryIdTracksIdQueryOptions(libraryId, id, options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Add track favorite by id
 */
export const postApiLibraryIdTracksIdFavorite = (
    libraryId: string,
    id: string,
    options?: SecondParameter<typeof apiInstance>,
) => {
    return apiInstance<PostApiLibraryIdTracksIdFavorite204>(
        { method: 'POST', url: `/api/${libraryId}/tracks/${id}/favorite` },
        options,
    );
};

export const getPostApiLibraryIdTracksIdFavoriteMutationOptions = <
    TError = ErrorType<
        | PostApiLibraryIdTracksIdFavorite401
        | PostApiLibraryIdTracksIdFavorite403
        | PostApiLibraryIdTracksIdFavorite404
        | PostApiLibraryIdTracksIdFavorite500
    >,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof postApiLibraryIdTracksIdFavorite>>,
        TError,
        { id: string; libraryId: string },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof postApiLibraryIdTracksIdFavorite>>,
    TError,
    { id: string; libraryId: string },
    TContext
> => {
    const { mutation: mutationOptions, request: requestOptions } = options ?? {};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof postApiLibraryIdTracksIdFavorite>>,
        { id: string; libraryId: string }
    > = (props) => {
        const { libraryId, id } = props ?? {};

        return postApiLibraryIdTracksIdFavorite(libraryId, id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PostApiLibraryIdTracksIdFavoriteMutationResult = NonNullable<
    Awaited<ReturnType<typeof postApiLibraryIdTracksIdFavorite>>
>;

export type PostApiLibraryIdTracksIdFavoriteMutationError = ErrorType<
    | PostApiLibraryIdTracksIdFavorite401
    | PostApiLibraryIdTracksIdFavorite403
    | PostApiLibraryIdTracksIdFavorite404
    | PostApiLibraryIdTracksIdFavorite500
>;

/**
 * @summary Add track favorite by id
 */
export const usePostApiLibraryIdTracksIdFavorite = <
    TError = ErrorType<
        | PostApiLibraryIdTracksIdFavorite401
        | PostApiLibraryIdTracksIdFavorite403
        | PostApiLibraryIdTracksIdFavorite404
        | PostApiLibraryIdTracksIdFavorite500
    >,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof postApiLibraryIdTracksIdFavorite>>,
        TError,
        { id: string; libraryId: string },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationResult<
    Awaited<ReturnType<typeof postApiLibraryIdTracksIdFavorite>>,
    TError,
    { id: string; libraryId: string },
    TContext
> => {
    const mutationOptions = getPostApiLibraryIdTracksIdFavoriteMutationOptions(options);

    return useMutation(mutationOptions);
};
/**
 * @summary Remove track favorite by id
 */
export const deleteApiLibraryIdTracksIdFavorite = (
    libraryId: string,
    id: string,
    options?: SecondParameter<typeof apiInstance>,
) => {
    return apiInstance<DeleteApiLibraryIdTracksIdFavorite204>(
        { method: 'DELETE', url: `/api/${libraryId}/tracks/${id}/favorite` },
        options,
    );
};

export const getDeleteApiLibraryIdTracksIdFavoriteMutationOptions = <
    TError = ErrorType<
        | DeleteApiLibraryIdTracksIdFavorite401
        | DeleteApiLibraryIdTracksIdFavorite403
        | DeleteApiLibraryIdTracksIdFavorite404
        | DeleteApiLibraryIdTracksIdFavorite500
    >,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteApiLibraryIdTracksIdFavorite>>,
        TError,
        { id: string; libraryId: string },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiLibraryIdTracksIdFavorite>>,
    TError,
    { id: string; libraryId: string },
    TContext
> => {
    const { mutation: mutationOptions, request: requestOptions } = options ?? {};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteApiLibraryIdTracksIdFavorite>>,
        { id: string; libraryId: string }
    > = (props) => {
        const { libraryId, id } = props ?? {};

        return deleteApiLibraryIdTracksIdFavorite(libraryId, id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteApiLibraryIdTracksIdFavoriteMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteApiLibraryIdTracksIdFavorite>>
>;

export type DeleteApiLibraryIdTracksIdFavoriteMutationError = ErrorType<
    | DeleteApiLibraryIdTracksIdFavorite401
    | DeleteApiLibraryIdTracksIdFavorite403
    | DeleteApiLibraryIdTracksIdFavorite404
    | DeleteApiLibraryIdTracksIdFavorite500
>;

/**
 * @summary Remove track favorite by id
 */
export const useDeleteApiLibraryIdTracksIdFavorite = <
    TError = ErrorType<
        | DeleteApiLibraryIdTracksIdFavorite401
        | DeleteApiLibraryIdTracksIdFavorite403
        | DeleteApiLibraryIdTracksIdFavorite404
        | DeleteApiLibraryIdTracksIdFavorite500
    >,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteApiLibraryIdTracksIdFavorite>>,
        TError,
        { id: string; libraryId: string },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationResult<
    Awaited<ReturnType<typeof deleteApiLibraryIdTracksIdFavorite>>,
    TError,
    { id: string; libraryId: string },
    TContext
> => {
    const mutationOptions = getDeleteApiLibraryIdTracksIdFavoriteMutationOptions(options);

    return useMutation(mutationOptions);
};
