/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Audioling API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type {
    DeleteApiUsersId204,
    DeleteApiUsersId401,
    DeleteApiUsersId403,
    DeleteApiUsersId404,
    DeleteApiUsersId500,
    GetApiUsers200,
    GetApiUsers401,
    GetApiUsers403,
    GetApiUsers422,
    GetApiUsers500,
    GetApiUsersId200,
    GetApiUsersId401,
    GetApiUsersId403,
    GetApiUsersId404,
    GetApiUsersId500,
    GetApiUsersParams,
    PostApiUsers201,
    PostApiUsers400,
    PostApiUsers401,
    PostApiUsers403,
    PostApiUsers409,
    PostApiUsers422,
    PostApiUsers500,
    PostApiUsersBody,
    PutApiUsersId200,
    PutApiUsersId400,
    PutApiUsersId401,
    PutApiUsersId403,
    PutApiUsersId404,
    PutApiUsersId422,
    PutApiUsersId500,
    PutApiUsersIdBody,
} from '../audioling-openapi-client.schemas.ts';
import { apiInstance } from '../../api-instance.ts';
import type { ErrorType, BodyType } from '../../api-instance.ts';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary Get all users
 */
export const getApiUsers = (
    params: GetApiUsersParams,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<GetApiUsers200>(
        { url: `/api/users`, method: 'GET', params, signal },
        options,
    );
};

export const getGetApiUsersQueryKey = (params: GetApiUsersParams) => {
    return [`/api/users`, ...(params ? [params] : [])] as const;
};

export const getGetApiUsersQueryOptions = <
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = ErrorType<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetApiUsersQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsers>>> = ({ signal }) =>
        getApiUsers(params, requestOptions, signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getApiUsers>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsers>>>;
export type GetApiUsersQueryError = ErrorType<
    GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500
>;

export function useGetApiUsers<
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = ErrorType<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsers<
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = ErrorType<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsers<
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = ErrorType<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all users
 */

export function useGetApiUsers<
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = ErrorType<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetApiUsersQueryOptions(params, options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getGetApiUsersSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = ErrorType<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetApiUsersQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsers>>> = ({ signal }) =>
        getApiUsers(params, requestOptions, signal);

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiUsers>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiUsersSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsers>>>;
export type GetApiUsersSuspenseQueryError = ErrorType<
    GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500
>;

export function useGetApiUsersSuspense<
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = ErrorType<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsersSuspense<
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = ErrorType<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsersSuspense<
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = ErrorType<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all users
 */

export function useGetApiUsersSuspense<
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = ErrorType<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetApiUsersSuspenseQueryOptions(params, options);

    const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Create user
 */
export const postApiUsers = (
    postApiUsersBody: BodyType<PostApiUsersBody>,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<PostApiUsers201>(
        {
            url: `/api/users`,
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            data: postApiUsersBody,
            signal,
        },
        options,
    );
};

export const getPostApiUsersMutationOptions = <
    TData = Awaited<ReturnType<typeof postApiUsers>>,
    TError = ErrorType<
        | PostApiUsers400
        | PostApiUsers401
        | PostApiUsers403
        | PostApiUsers409
        | PostApiUsers422
        | PostApiUsers500
    >,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<TData, TError, { data: BodyType<PostApiUsersBody> }, TContext>;
    request?: SecondParameter<typeof apiInstance>;
}) => {
    const mutationKey = ['postApiUsers'];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof postApiUsers>>,
        { data: BodyType<PostApiUsersBody> }
    > = (props) => {
        const { data } = props ?? {};

        return postApiUsers(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions } as UseMutationOptions<
        TData,
        TError,
        { data: BodyType<PostApiUsersBody> },
        TContext
    >;
};

export type PostApiUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUsers>>>;
export type PostApiUsersMutationBody = BodyType<PostApiUsersBody>;
export type PostApiUsersMutationError = ErrorType<
    | PostApiUsers400
    | PostApiUsers401
    | PostApiUsers403
    | PostApiUsers409
    | PostApiUsers422
    | PostApiUsers500
>;

/**
 * @summary Create user
 */
export const usePostApiUsers = <
    TData = Awaited<ReturnType<typeof postApiUsers>>,
    TError = ErrorType<
        | PostApiUsers400
        | PostApiUsers401
        | PostApiUsers403
        | PostApiUsers409
        | PostApiUsers422
        | PostApiUsers500
    >,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<TData, TError, { data: BodyType<PostApiUsersBody> }, TContext>;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationResult<TData, TError, { data: BodyType<PostApiUsersBody> }, TContext> => {
    const mutationOptions = getPostApiUsersMutationOptions(options);

    return useMutation(mutationOptions);
};
/**
 * @summary Get user by id
 */
export const getApiUsersId = (
    id: string,
    options?: SecondParameter<typeof apiInstance>,
    signal?: AbortSignal,
) => {
    return apiInstance<GetApiUsersId200>(
        { url: `/api/users/${id}`, method: 'GET', signal },
        options,
    );
};

export const getGetApiUsersIdQueryKey = (id: string) => {
    return [`/api/users/${id}`] as const;
};

export const getGetApiUsersIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = ErrorType<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>>;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetApiUsersIdQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsersId>>> = ({ signal }) =>
        getApiUsersId(id, requestOptions, signal);

    return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getApiUsersId>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiUsersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsersId>>>;
export type GetApiUsersIdQueryError = ErrorType<
    GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500
>;

export function useGetApiUsersId<
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = ErrorType<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsersId<
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = ErrorType<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getApiUsersId>>,
                    TError,
                    TData
                >,
                'initialData'
            >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsersId<
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = ErrorType<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>>;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get user by id
 */

export function useGetApiUsersId<
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = ErrorType<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>>;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetApiUsersIdQueryOptions(id, options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getGetApiUsersIdSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = ErrorType<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetApiUsersIdQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsersId>>> = ({ signal }) =>
        getApiUsersId(id, requestOptions, signal);

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiUsersId>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiUsersIdSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof getApiUsersId>>
>;
export type GetApiUsersIdSuspenseQueryError = ErrorType<
    GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500
>;

export function useGetApiUsersIdSuspense<
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = ErrorType<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsersIdSuspense<
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = ErrorType<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsersIdSuspense<
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = ErrorType<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get user by id
 */

export function useGetApiUsersIdSuspense<
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = ErrorType<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>
        >;
        request?: SecondParameter<typeof apiInstance>;
    },
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetApiUsersIdSuspenseQueryOptions(id, options);

    const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Delete user by id
 */
export const deleteApiUsersId = (id: string, options?: SecondParameter<typeof apiInstance>) => {
    return apiInstance<DeleteApiUsersId204>({ url: `/api/users/${id}`, method: 'DELETE' }, options);
};

export const getDeleteApiUsersIdMutationOptions = <
    TData = Awaited<ReturnType<typeof deleteApiUsersId>>,
    TError = ErrorType<
        DeleteApiUsersId401 | DeleteApiUsersId403 | DeleteApiUsersId404 | DeleteApiUsersId500
    >,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<TData, TError, { id: string }, TContext>;
    request?: SecondParameter<typeof apiInstance>;
}) => {
    const mutationKey = ['deleteApiUsersId'];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteApiUsersId>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {};

        return deleteApiUsersId(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions } as UseMutationOptions<
        TData,
        TError,
        { id: string },
        TContext
    >;
};

export type DeleteApiUsersIdMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteApiUsersId>>
>;

export type DeleteApiUsersIdMutationError = ErrorType<
    DeleteApiUsersId401 | DeleteApiUsersId403 | DeleteApiUsersId404 | DeleteApiUsersId500
>;

/**
 * @summary Delete user by id
 */
export const useDeleteApiUsersId = <
    TData = Awaited<ReturnType<typeof deleteApiUsersId>>,
    TError = ErrorType<
        DeleteApiUsersId401 | DeleteApiUsersId403 | DeleteApiUsersId404 | DeleteApiUsersId500
    >,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<TData, TError, { id: string }, TContext>;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationResult<TData, TError, { id: string }, TContext> => {
    const mutationOptions = getDeleteApiUsersIdMutationOptions(options);

    return useMutation(mutationOptions);
};
/**
 * @summary Update user by id
 */
export const putApiUsersId = (
    id: string,
    putApiUsersIdBody: BodyType<PutApiUsersIdBody>,
    options?: SecondParameter<typeof apiInstance>,
) => {
    return apiInstance<PutApiUsersId200>(
        {
            url: `/api/users/${id}`,
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            data: putApiUsersIdBody,
        },
        options,
    );
};

export const getPutApiUsersIdMutationOptions = <
    TData = Awaited<ReturnType<typeof putApiUsersId>>,
    TError = ErrorType<
        | PutApiUsersId400
        | PutApiUsersId401
        | PutApiUsersId403
        | PutApiUsersId404
        | PutApiUsersId422
        | PutApiUsersId500
    >,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        TData,
        TError,
        { id: string; data: BodyType<PutApiUsersIdBody> },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}) => {
    const mutationKey = ['putApiUsersId'];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof putApiUsersId>>,
        { id: string; data: BodyType<PutApiUsersIdBody> }
    > = (props) => {
        const { id, data } = props ?? {};

        return putApiUsersId(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions } as UseMutationOptions<
        TData,
        TError,
        { id: string; data: BodyType<PutApiUsersIdBody> },
        TContext
    >;
};

export type PutApiUsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiUsersId>>>;
export type PutApiUsersIdMutationBody = BodyType<PutApiUsersIdBody>;
export type PutApiUsersIdMutationError = ErrorType<
    | PutApiUsersId400
    | PutApiUsersId401
    | PutApiUsersId403
    | PutApiUsersId404
    | PutApiUsersId422
    | PutApiUsersId500
>;

/**
 * @summary Update user by id
 */
export const usePutApiUsersId = <
    TData = Awaited<ReturnType<typeof putApiUsersId>>,
    TError = ErrorType<
        | PutApiUsersId400
        | PutApiUsersId401
        | PutApiUsersId403
        | PutApiUsersId404
        | PutApiUsersId422
        | PutApiUsersId500
    >,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        TData,
        TError,
        { id: string; data: BodyType<PutApiUsersIdBody> },
        TContext
    >;
    request?: SecondParameter<typeof apiInstance>;
}): UseMutationResult<
    TData,
    TError,
    { id: string; data: BodyType<PutApiUsersIdBody> },
    TContext
> => {
    const mutationOptions = getPutApiUsersIdMutationOptions(options);

    return useMutation(mutationOptions);
};
