/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Audioling API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type {
    DeleteApiUsersId204,
    DeleteApiUsersId401,
    DeleteApiUsersId403,
    DeleteApiUsersId404,
    DeleteApiUsersId500,
    GetApiUsers200,
    GetApiUsers401,
    GetApiUsers403,
    GetApiUsers422,
    GetApiUsers500,
    GetApiUsersId200,
    GetApiUsersId401,
    GetApiUsersId403,
    GetApiUsersId404,
    GetApiUsersId500,
    GetApiUsersParams,
    PostApiUsers201,
    PostApiUsers400,
    PostApiUsers401,
    PostApiUsers403,
    PostApiUsers409,
    PostApiUsers422,
    PostApiUsers500,
    PostApiUsersBody,
    PutApiUsersId200,
    PutApiUsersId400,
    PutApiUsersId401,
    PutApiUsersId403,
    PutApiUsersId404,
    PutApiUsersId422,
    PutApiUsersId500,
    PutApiUsersIdBody,
} from '../audioling-openapi-client.schemas.ts';

/**
 * @summary Get all users
 */
export const getApiUsers = (
    params: GetApiUsersParams,
    options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetApiUsers200>> => {
    return axios.get(`/api/users`, {
        ...options,
        params: { ...params, ...options?.params },
    });
};

export const getGetApiUsersQueryKey = (params: GetApiUsersParams) => {
    return [`/api/users`, ...(params ? [params] : [])] as const;
};

export const getGetApiUsersQueryOptions = <
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = AxiosError<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options?: {
        axios?: AxiosRequestConfig;
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>;
    },
) => {
    const { query: queryOptions, axios: axiosOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetApiUsersQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsers>>> = ({ signal }) =>
        getApiUsers(params, { signal, ...axiosOptions });

    return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getApiUsers>>,
        TError,
        TData
    > & { queryKey: QueryKey };
};

export type GetApiUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsers>>>;
export type GetApiUsersQueryError = AxiosError<
    GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500
>;

export function useGetApiUsers<
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = AxiosError<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options: {
        axios?: AxiosRequestConfig;
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>,
                'initialData'
            >;
    },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetApiUsers<
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = AxiosError<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options?: {
        axios?: AxiosRequestConfig;
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>,
                'initialData'
            >;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetApiUsers<
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = AxiosError<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options?: {
        axios?: AxiosRequestConfig;
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get all users
 */

export function useGetApiUsers<
    TData = Awaited<ReturnType<typeof getApiUsers>>,
    TError = AxiosError<GetApiUsers401 | GetApiUsers403 | GetApiUsers422 | GetApiUsers500>,
>(
    params: GetApiUsersParams,
    options?: {
        axios?: AxiosRequestConfig;
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
    const queryOptions = getGetApiUsersQueryOptions(params, options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Create user
 */
export const postApiUsers = (
    postApiUsersBody: PostApiUsersBody,
    options?: AxiosRequestConfig,
): Promise<AxiosResponse<PostApiUsers201>> => {
    return axios.post(`/api/users`, postApiUsersBody, options);
};

export const getPostApiUsersMutationOptions = <
    TError = AxiosError<
        | PostApiUsers400
        | PostApiUsers401
        | PostApiUsers403
        | PostApiUsers409
        | PostApiUsers422
        | PostApiUsers500
    >,
    TContext = unknown,
>(options?: {
    axios?: AxiosRequestConfig;
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof postApiUsers>>,
        TError,
        { data: PostApiUsersBody },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof postApiUsers>>,
    TError,
    { data: PostApiUsersBody },
    TContext
> => {
    const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof postApiUsers>>,
        { data: PostApiUsersBody }
    > = (props) => {
        const { data } = props ?? {};

        return postApiUsers(data, axiosOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PostApiUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUsers>>>;
export type PostApiUsersMutationBody = PostApiUsersBody;
export type PostApiUsersMutationError = AxiosError<
    | PostApiUsers400
    | PostApiUsers401
    | PostApiUsers403
    | PostApiUsers409
    | PostApiUsers422
    | PostApiUsers500
>;

/**
 * @summary Create user
 */
export const usePostApiUsers = <
    TError = AxiosError<
        | PostApiUsers400
        | PostApiUsers401
        | PostApiUsers403
        | PostApiUsers409
        | PostApiUsers422
        | PostApiUsers500
    >,
    TContext = unknown,
>(options?: {
    axios?: AxiosRequestConfig;
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof postApiUsers>>,
        TError,
        { data: PostApiUsersBody },
        TContext
    >;
}): UseMutationResult<
    Awaited<ReturnType<typeof postApiUsers>>,
    TError,
    { data: PostApiUsersBody },
    TContext
> => {
    const mutationOptions = getPostApiUsersMutationOptions(options);

    return useMutation(mutationOptions);
};
/**
 * @summary Get user by id
 */
export const getApiUsersId = (
    id: string,
    options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetApiUsersId200>> => {
    return axios.get(`/api/users/${id}`, options);
};

export const getGetApiUsersIdQueryKey = (id: string) => {
    return [`/api/users/${id}`] as const;
};

export const getGetApiUsersIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = AxiosError<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options?: {
        axios?: AxiosRequestConfig;
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>>;
    },
) => {
    const { query: queryOptions, axios: axiosOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetApiUsersIdQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsersId>>> = ({ signal }) =>
        getApiUsersId(id, { signal, ...axiosOptions });

    return { enabled: !!id, queryFn, queryKey, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getApiUsersId>>,
        TError,
        TData
    > & { queryKey: QueryKey };
};

export type GetApiUsersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsersId>>>;
export type GetApiUsersIdQueryError = AxiosError<
    GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500
>;

export function useGetApiUsersId<
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = AxiosError<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options: {
        axios?: AxiosRequestConfig;
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>,
                'initialData'
            >;
    },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetApiUsersId<
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = AxiosError<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options?: {
        axios?: AxiosRequestConfig;
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getApiUsersId>>,
                    TError,
                    TData
                >,
                'initialData'
            >;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetApiUsersId<
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = AxiosError<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options?: {
        axios?: AxiosRequestConfig;
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>>;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get user by id
 */

export function useGetApiUsersId<
    TData = Awaited<ReturnType<typeof getApiUsersId>>,
    TError = AxiosError<GetApiUsersId401 | GetApiUsersId403 | GetApiUsersId404 | GetApiUsersId500>,
>(
    id: string,
    options?: {
        axios?: AxiosRequestConfig;
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersId>>, TError, TData>>;
    },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
    const queryOptions = getGetApiUsersIdQueryOptions(id, options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * @summary Delete user by id
 */
export const deleteApiUsersId = (
    id: string,
    options?: AxiosRequestConfig,
): Promise<AxiosResponse<DeleteApiUsersId204>> => {
    return axios.delete(`/api/users/${id}`, options);
};

export const getDeleteApiUsersIdMutationOptions = <
    TError = AxiosError<
        DeleteApiUsersId401 | DeleteApiUsersId403 | DeleteApiUsersId404 | DeleteApiUsersId500
    >,
    TContext = unknown,
>(options?: {
    axios?: AxiosRequestConfig;
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteApiUsersId>>,
        TError,
        { id: string },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiUsersId>>,
    TError,
    { id: string },
    TContext
> => {
    const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteApiUsersId>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {};

        return deleteApiUsersId(id, axiosOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteApiUsersIdMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteApiUsersId>>
>;

export type DeleteApiUsersIdMutationError = AxiosError<
    DeleteApiUsersId401 | DeleteApiUsersId403 | DeleteApiUsersId404 | DeleteApiUsersId500
>;

/**
 * @summary Delete user by id
 */
export const useDeleteApiUsersId = <
    TError = AxiosError<
        DeleteApiUsersId401 | DeleteApiUsersId403 | DeleteApiUsersId404 | DeleteApiUsersId500
    >,
    TContext = unknown,
>(options?: {
    axios?: AxiosRequestConfig;
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteApiUsersId>>,
        TError,
        { id: string },
        TContext
    >;
}): UseMutationResult<
    Awaited<ReturnType<typeof deleteApiUsersId>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationOptions = getDeleteApiUsersIdMutationOptions(options);

    return useMutation(mutationOptions);
};
/**
 * @summary Update user by id
 */
export const putApiUsersId = (
    id: string,
    putApiUsersIdBody: PutApiUsersIdBody,
    options?: AxiosRequestConfig,
): Promise<AxiosResponse<PutApiUsersId200>> => {
    return axios.put(`/api/users/${id}`, putApiUsersIdBody, options);
};

export const getPutApiUsersIdMutationOptions = <
    TError = AxiosError<
        | PutApiUsersId400
        | PutApiUsersId401
        | PutApiUsersId403
        | PutApiUsersId404
        | PutApiUsersId422
        | PutApiUsersId500
    >,
    TContext = unknown,
>(options?: {
    axios?: AxiosRequestConfig;
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof putApiUsersId>>,
        TError,
        { data: PutApiUsersIdBody; id: string },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof putApiUsersId>>,
    TError,
    { data: PutApiUsersIdBody; id: string },
    TContext
> => {
    const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof putApiUsersId>>,
        { data: PutApiUsersIdBody; id: string }
    > = (props) => {
        const { id, data } = props ?? {};

        return putApiUsersId(id, data, axiosOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PutApiUsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiUsersId>>>;
export type PutApiUsersIdMutationBody = PutApiUsersIdBody;
export type PutApiUsersIdMutationError = AxiosError<
    | PutApiUsersId400
    | PutApiUsersId401
    | PutApiUsersId403
    | PutApiUsersId404
    | PutApiUsersId422
    | PutApiUsersId500
>;

/**
 * @summary Update user by id
 */
export const usePutApiUsersId = <
    TError = AxiosError<
        | PutApiUsersId400
        | PutApiUsersId401
        | PutApiUsersId403
        | PutApiUsersId404
        | PutApiUsersId422
        | PutApiUsersId500
    >,
    TContext = unknown,
>(options?: {
    axios?: AxiosRequestConfig;
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof putApiUsersId>>,
        TError,
        { data: PutApiUsersIdBody; id: string },
        TContext
    >;
}): UseMutationResult<
    Awaited<ReturnType<typeof putApiUsersId>>,
    TError,
    { data: PutApiUsersIdBody; id: string },
    TContext
> => {
    const mutationOptions = getPutApiUsersIdMutationOptions(options);

    return useMutation(mutationOptions);
};
