import type { AppThemeConfiguration } from '@/themes/index.ts';

const primaryColor = 'rgb(226, 226, 226)';
const dangerColor = 'rgb(197, 15, 31)';

const gap = {
    lg: '2rem',
    md: '1rem',
    sm: '0.5rem',
    xl: '4rem',
    xs: '0.25rem',
};

const fontSize = {
    lg: '1.25rem',
    md: '1rem',
    sm: '0.875rem',
    xl: '1.5rem',
    xs: '0.75rem',
};

const radius = {
    lg: '0.75rem',
    md: '0.25rem',
    sm: '0.125rem',
    xl: '1rem',
    xs: '0rem',
};

export const baseTheme: AppThemeConfiguration['theme'] = {
    'base-border-radius-lg': radius.lg,
    'base-border-radius-md': radius.md,
    'base-border-radius-sm': radius.sm,
    'base-border-radius-xl': radius.xl,
    'base-border-radius-xs': radius.xs,
    'base-font-size-lg': fontSize.lg,
    'base-font-size-md': fontSize.md,
    'base-font-size-sm': fontSize.sm,
    'base-font-size-xl': fontSize.xl,
    'base-font-size-xs': fontSize.xs,
    'base-font-weight-lg': '500',
    'base-font-weight-md': '400',
    'base-font-weight-sm': '300',
    'base-font-weight-xl': '600',
    'base-font-weight-xs': '200',
    'base-gap-lg': gap.lg,
    'base-gap-md': gap.md,
    'base-gap-sm': gap.sm,
    'base-gap-xl': gap.xl,
    'base-gap-xs': gap.xs,
    'base-title-font-size-lg': '2rem',
    'base-title-font-size-md': '1.5rem',
    'base-title-font-size-sm': '1rem',
    'base-title-font-size-xl': '2.5rem',
    'base-title-font-size-xs': '1.25rem',
    'base-title-font-weight-lg': '700',
    'base-title-font-weight-md': '600',
    'base-title-font-weight-sm': '500',
    'base-title-font-weight-xl': '800',
    'base-title-font-weight-xs': '400',
    'button-danger-background-color': dangerColor,
    'button-danger-border': `1px solid ${dangerColor}`,
    'button-danger-font-color': 'rgb(230, 230, 230)',
    'button-danger-hover-background-color': 'rgba(197, 15, 31, 0.8)',
    'button-danger-hover-border': '1px solid rgb(197, 15, 31)',
    'button-danger-hover-font-color': 'rgb(230, 230, 230)',
    'button-default-background-color': 'rgba(0, 0, 0, 0)',
    'button-default-border': '1px solid rgba(0, 0, 0, 0)',
    'button-default-font-color': 'rgb(230, 230, 230)',
    'button-default-hover-background-color': 'rgb(25, 25, 25)',
    'button-default-hover-border': '1px solid rgba(0, 0, 0, 0)',
    'button-default-hover-font-color': 'rgb(230, 230, 230)',
    'button-filled-background-color': primaryColor,
    'button-filled-border': `1px solid ${primaryColor}`,
    'button-filled-font-color': 'rgb(25, 25, 25)',
    'button-filled-hover-background-color': 'rgb(200, 200, 200)',
    'button-filled-hover-border': '1px solid rgb(0, 0, 0)',
    'button-filled-hover-font-color': 'rgb(25, 25, 25)',
    'global-background-color': 'rgb(16, 16, 16)',
    'global-danger-color': dangerColor,
    'global-font-color': 'rgb(230, 230, 230)',
    'global-font-family': 'Poppins',
    'global-font-secondary-color': 'rgb(120, 120, 120)',
    'global-font-size': '16px',
    'global-info-color': 'rgb(50, 50, 204)',
    'global-primary-color': 'rgb(50, 50, 204)',
    'global-success-color': 'rgb(50, 204, 50)',
    'global-warning-color': 'rgb(204, 204, 50)',
    'input-background-color': 'rgb(29, 29, 32)',
    'input-border': '1px solid rgb(0, 0, 0)',
    'input-font-color': 'rgb(230, 230, 230)',
    'input-hover-background-color': 'rgb(34, 34, 37)',
    'input-hover-font-color': 'rgb(230, 230, 230)',
    'input-hover-placeholder-color': 'rgb(230, 230, 230)',
    'input-placeholder-color': 'rgb(77, 77, 77)',
    'layout-header-height': '50px',
    'layout-player-bar-background-color': 'rgb(8, 8, 8)',
    'layout-player-bar-border-bottom': '1px solid rgb(0, 0, 0)',
    'layout-player-bar-border-left': '1px solid rgb(0, 0, 0)',
    'layout-player-bar-border-radius': '0',
    'layout-player-bar-border-right': '1px solid rgb(0, 0, 0)',
    'layout-player-bar-border-top': '1px solid rgb(0, 0, 0)',
    'layout-player-bar-height': '85px',
    'layout-player-bar-margin': '0',
    'layout-player-bar-padding': gap.md,
    'layout-side-bar-left-background-color': 'rgb(50, 50, 50)',
    'layout-side-bar-left-font-color': 'rgb(255, 255, 255)',
    'layout-side-bar-left-font-hover-color': 'rgb(255, 255, 255)',
    'layout-side-bar-left-width': '300px',
    'layout-side-bar-right-background-color': 'rgb(50, 50, 50)',
    'layout-side-bar-right-width': '300px',
    'scroll-bar-size': '12px',
    'scroll-bar-thumb-active-background-color': 'rgba(160, 160, 160, 0.6)',
    'scroll-bar-thumb-background-color': 'rgba(160, 160, 160, 0.2)',
    'scroll-bar-thumb-hover-background-color': 'rgba(160, 160, 160, 0.4)',
    'scroll-bar-track-active-background-color': 'rgba(0, 0, 0, 0)',
    'scroll-bar-track-background-color': 'rgba(0, 0, 0, 0)',
    'scroll-bar-track-hover-background-color': 'rgba(0, 0, 0, 0)',
    'table-border-color': primaryColor,
    'table-cell-border-color': primaryColor,
    'table-header-background-color': 'rgb(50, 50, 50)',
    'table-header-font-color': 'rgb(230, 230, 230)',
    'table-row-background-color': 'rgb(50, 50, 50)',
    'table-row-border-color': primaryColor,
    'table-row-font-color': 'rgb(230, 230, 230)',
    'table-row-hover-background-color': 'rgb(60, 60, 60)',
    'table-row-hover-border-color': primaryColor,
    'table-row-hover-font-color': 'rgb(230, 230, 230)',
    'table-row-selected-background-color': 'rgba(60, 60, 60, 0.3)',
    'table-row-selected-border-color': primaryColor,
    'table-row-selected-font-color': 'rgb(255, 255, 255)',
};
