import { AlbumListSortOptions, type AppServerConfig, ArtistListSortOptions, ServerType } from './_app-types.js';
import JellyfinLogo from './assets/jellyfin.png';
import NavidromeLogo from './assets/navidrome.png';
import OpenSubsonicLogo from './assets/opensubsonic.png';

export const SERVER_CONFIG: AppServerConfig = {
    [ServerType.JELLYFIN]: {
        features: {
            'album:detail': true,
            'album:detail:favorites': true,
            'album:detail:ratings': true,
            'album:list': true,
            'album:list:sort': {},
            'albumArtist:detail': true,
            'albumArtist:detail:favorites': true,
            'albumArtist:detail:ratings': true,
            'albumArtist:list': true,
            'albumArtist:list:sort': {},
            'artist:detail': true,
            'artist:detail:favorites': true,
            'artist:detail:ratings': true,
            'artist:list': true,
            'artist:list:sort': {},
            'genre:detail': true,
            'genre:list': true,
            'genre:list:sort': {},
            'playlist:create': true,
            'playlist:delete': true,
            'playlist:detail': true,
            'playlist:list': true,
            'playlist:list:sort': {},
            'track:detail': true,
            'track:detail:favorites': true,
            'track:detail:ratings': true,
            'track:list': true,
            'track:list:sort': {},
        },
        logo: JellyfinLogo,
        name: 'Jellyfin',
    },
    [ServerType.NAVIDROME]: {
        features: {
            'album:detail': true,
            'album:detail:favorites': true,
            'album:detail:ratings': true,
            'album:list': true,
            'album:list:sort': {},
            'albumArtist:detail': true,
            'albumArtist:detail:favorites': true,
            'albumArtist:detail:ratings': true,
            'albumArtist:list': true,
            'albumArtist:list:sort': {},
            'artist:detail': true,
            'artist:detail:favorites': true,
            'artist:detail:ratings': true,
            'artist:list': true,
            'artist:list:sort': {},
            'genre:detail': true,
            'genre:list': true,
            'genre:list:sort': {},
            'playlist:create': true,
            'playlist:delete': true,
            'playlist:detail': true,
            'playlist:list': true,
            'playlist:list:sort': {},
            'track:detail': true,
            'track:detail:favorites': true,
            'track:detail:ratings': true,
            'track:list': true,
            'track:list:sort': {},
        },
        logo: NavidromeLogo,
        name: 'Navidrome',
    },
    [ServerType.OPENSUBSONIC]: {
        features: {
            'album:detail': true,
            'album:detail:favorites': true,
            'album:detail:ratings': true,
            'album:list': true,
            'album:list:sort': {
                [AlbumListSortOptions.DATE_ADDED]: {
                    label: 'Date Added',
                    property: 'newest',
                },
                [AlbumListSortOptions.DATE_PLAYED]: {
                    label: 'Date Played',
                    property: 'recent',
                },
                [AlbumListSortOptions.IS_FAVORITE]: {
                    label: 'Favorite',
                    property: 'starred',
                },
                [AlbumListSortOptions.NAME]: {
                    label: 'Name',
                    property: 'alphabeticalByName',
                },
                [AlbumListSortOptions.RATING]: {
                    label: 'Rating',
                    property: 'highest',
                },
                [AlbumListSortOptions.PLAY_COUNT]: {
                    label: 'Play Count',
                    property: 'frequent',
                },
                [AlbumListSortOptions.YEAR]: {
                    label: 'Year',
                    property: 'byYear',
                },
            },
            'albumArtist:detail': true,
            'albumArtist:detail:favorites': true,
            'albumArtist:detail:ratings': true,
            'albumArtist:list': true,
            'albumArtist:list:sort': {
                [ArtistListSortOptions.NAME]: {
                    label: 'Name',
                    property: 'alphabeticalByName',
                },
                [ArtistListSortOptions.ALBUM_COUNT]: {
                    label: 'Album Count',
                    property: 'albumCount',
                },
                [ArtistListSortOptions.TRACK_COUNT]: {
                    label: 'Track Count',
                    property: 'trackCount',
                },
            },
            'artist:detail': true,
            'artist:detail:favorites': true,
            'artist:detail:ratings': true,
            'artist:list': true,
            'artist:list:sort': {},
            'genre:detail': true,
            'genre:list': true,
            'genre:list:sort': {},
            'playlist:create': true,
            'playlist:delete': true,
            'playlist:detail': true,
            'playlist:list': true,
            'playlist:list:sort': {},
            'track:detail': true,
            'track:detail:favorites': true,
            'track:detail:ratings': true,
            'track:list': true,
            'track:list:sort': {},
        },
        logo: OpenSubsonicLogo,
        name: 'OpenSubsonic',
    },
};
