/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Audioling API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
} from '@tanstack/react-query';
import { apiInstance } from '../../api-instance.ts';
import type { ErrorType } from '../../api-instance.ts';
import type { GetPing200 } from '../audioling-openapi-client.schemas.ts';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary Ping the server
 */
export const getPing = (options?: SecondParameter<typeof apiInstance>, signal?: AbortSignal) => {
    return apiInstance<GetPing200>({ method: 'GET', signal, url: `/ping` }, options);
};

export const getGetPingQueryKey = () => {
    return [`/ping`] as const;
};

export const getGetPingQueryOptions = <
    TData = Awaited<ReturnType<typeof getPing>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPing>>, TError, TData>>;
    request?: SecondParameter<typeof apiInstance>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetPingQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPing>>> = ({ signal }) =>
        getPing(requestOptions, signal);

    return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getPing>>,
        TError,
        TData
    > & { queryKey: QueryKey };
};

export type GetPingQueryResult = NonNullable<Awaited<ReturnType<typeof getPing>>>;
export type GetPingQueryError = ErrorType<unknown>;

export function useGetPing<
    TData = Awaited<ReturnType<typeof getPing>>,
    TError = ErrorType<unknown>,
>(options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPing>>, TError, TData>> &
        Pick<
            DefinedInitialDataOptions<Awaited<ReturnType<typeof getPing>>, TError, TData>,
            'initialData'
        >;
    request?: SecondParameter<typeof apiInstance>;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetPing<
    TData = Awaited<ReturnType<typeof getPing>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPing>>, TError, TData>> &
        Pick<
            UndefinedInitialDataOptions<Awaited<ReturnType<typeof getPing>>, TError, TData>,
            'initialData'
        >;
    request?: SecondParameter<typeof apiInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetPing<
    TData = Awaited<ReturnType<typeof getPing>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPing>>, TError, TData>>;
    request?: SecondParameter<typeof apiInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Ping the server
 */

export function useGetPing<
    TData = Awaited<ReturnType<typeof getPing>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPing>>, TError, TData>>;
    request?: SecondParameter<typeof apiInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
    const queryOptions = getGetPingQueryOptions(options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

    query.queryKey = queryOptions.queryKey;

    return query;
}
